// Application-level DI configuration (alternative to main.ts providers)
// Note 1: appConfig is an ApplicationConfig object that can be passed to
// bootstrapApplication() as an alternative to inline providers. It is
// generated by 'ng new' but in this project, main.ts uses its own inline
// providers array instead. This file is kept for reference but its contents
// are not actively used — see main.ts for the actual provider configuration.
import { ApplicationConfig, provideBrowserGlobalErrorListeners } from '@angular/core';
import { provideRouter } from '@angular/router';

import { routes } from './app.routes';

// Note 2: provideBrowserGlobalErrorListeners() sets up window.onerror and
// window.onunhandledrejection handlers so Angular can catch and report
// uncaught errors from outside the Angular zone (e.g. third-party scripts).
export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideRouter(routes)
  ]
};
